/**
 * Geopolitical Conflict Monitor — Mock Data Service
 *
 * Design rules enforced in this file:
 * 1. All tensions are grouped by CONTINENT — never returned as a flat list.
 * 2. EVERY GeopoliticalEvent.sources array contains at least one Source
 *    with both `publisher` and `url` fields populated.
 * 3. Data represents realistic 2024–2026 geopolitical tensions.
 */

import type {
  ContinentSection,
  ConflictTension,
  MonitorFilterState,
} from '@/types/geopolitical';

// ─── Raw data, grouped by continent ──────────────────────────────────────────

export const CONTINENT_SECTIONS: ContinentSection[] = [
  // ═══════════════════════════════════════════════════════════════════════════
  // EUROPE
  // ═══════════════════════════════════════════════════════════════════════════
  {
    continent: 'Europe',
    tensions: [
      {
        id: 'russo-ukrainian-war',
        name: 'Russo-Ukrainian War',
        continent: 'Europe',
        status: 'critical',
        severity: 'high',
        startDate: '2022-02-24',
        lastUpdated: '2026-02-19',
        description:
          "Russia's full-scale invasion of Ukraine has entered its fourth year. Front lines remain largely static across the Zaporizhzhia, Kherson, Donetsk, and Luhansk oblasts, while long-range strikes continue to target Ukrainian energy infrastructure. NATO member states continue supplying weapons and financial aid, and ceasefire negotiations remain deadlocked.",
        countries: [
          { name: 'Ukraine', flag: '🇺🇦', role: 'Defender' },
          { name: 'Russia', flag: '🇷🇺', role: 'Aggressor' },
          { name: 'United States', flag: '🇺🇸', role: 'Ally' },
          { name: 'NATO', flag: '🌐', role: 'Ally' },
          { name: 'Belarus', flag: '🇧🇾', role: 'Ally' },
        ],
        tags: ['NATO', 'sanctions', 'energy war', 'drone warfare', 'nuclear threat'],
        events: [
          {
            id: 'ruw-001',
            date: '2026-02-19',
            headline: 'Ukraine strikes Russian oil depot 800 km behind front lines using domestic drones',
            summary:
              "Ukraine's unmanned aerial forces conducted a coordinated strike on a fuel storage facility in the Saratov region, marking one of the deepest penetrations of Russian territory since the start of the war. Russia denied significant damage.",
            sources: [
              { publisher: 'Reuters', url: 'https://www.reuters.com/world/europe/' },
              { publisher: 'Kyiv Independent', url: 'https://kyivindependent.com/' },
            ],
          },
          {
            id: 'ruw-002',
            date: '2026-02-14',
            headline: 'EU approves €20B in long-term loans for Ukraine from frozen Russian assets',
            summary:
              'European Union finance ministers greenlit a new tranche of financial support for Kyiv, drawing on interest generated by approximately €300B in immobilized Russian central bank assets held within the EU.',
            sources: [
              { publisher: 'Financial Times', url: 'https://www.ft.com/ukraine' },
              { publisher: 'European Parliament', url: 'https://www.europarl.europa.eu/news/' },
            ],
          },
          {
            id: 'ruw-003',
            date: '2026-02-05',
            headline: 'Russia deploys North Korean troops to Kursk front, NATO confirms',
            summary:
              'NATO Secretary General confirmed that an estimated 12,000 North Korean soldiers are now operating alongside Russian forces in the Kursk Oblast. South Korea, the US, and UK issued joint condemnation and pledged additional military aid.',
            sources: [
              { publisher: 'BBC News', url: 'https://www.bbc.com/news/world/europe' },
              { publisher: 'NATO Official Statement', url: 'https://www.nato.int/cps/en/natohq/news.htm' },
            ],
          },
        ],
      },
      {
        id: 'kosovo-serbia-standoff',
        name: 'Kosovo–Serbia Standoff',
        continent: 'Europe',
        status: 'elevated',
        severity: 'medium',
        startDate: '2022-09-01',
        lastUpdated: '2026-01-30',
        description:
          "Relations between Kosovo and Serbia remain acutely tense following repeated incidents at the northern border crossings, the ongoing dispute over Serbian Orthodox Church property, and Belgrade's refusal to recognize Kosovo statehood. KFOR (NATO's peacekeeping force) has increased patrol frequency.",
        countries: [
          { name: 'Kosovo', flag: '🇽🇰', role: 'Belligerent' },
          { name: 'Serbia', flag: '🇷🇸', role: 'Belligerent' },
          { name: 'EU', flag: '🇪🇺', role: 'Mediator' },
          { name: 'NATO / KFOR', flag: '🌐', role: 'Observer' },
        ],
        tags: ['Western Balkans', 'border dispute', 'KFOR', 'EU accession'],
        events: [
          {
            id: 'ks-001',
            date: '2026-01-30',
            headline: 'Serbia deploys armored units near administrative line with Kosovo',
            summary:
              "Serbian armed forces moved BTR-80 armored personnel carriers to the Merdare crossing area. Kosovo's government declared the deployment a \"blatant provocation\" and requested an emergency KFOR consultation.",
            sources: [
              { publisher: 'Balkan Insight', url: 'https://balkaninsight.com/' },
              { publisher: 'Radio Free Europe / RFE·RL', url: 'https://www.rferl.org/' },
            ],
          },
          {
            id: 'ks-002',
            date: '2026-01-15',
            headline: 'EU-brokered talks collapse after Serbia rejects association agreement clause',
            summary:
              'A Brussels-hosted dialogue session ended without agreement after Serbian negotiators refused to accept language on the Association of Serbian Municipalities that Kosovo argues would create a "state within a state."',
            sources: [
              { publisher: 'Reuters', url: 'https://www.reuters.com/world/europe/' },
              { publisher: 'EURACTIV', url: 'https://www.euractiv.com/' },
            ],
          },
        ],
      },
      {
        id: 'georgia-political-crisis',
        name: 'Georgia Democratic Backsliding',
        continent: 'Europe',
        status: 'watchlist',
        severity: 'medium',
        startDate: '2024-11-28',
        lastUpdated: '2026-01-22',
        description:
          "The ruling Georgian Dream party's suspension of EU accession negotiations until 2028 triggered mass protests in Tbilisi and other cities. The EU and US imposed sanctions on several Georgian officials. President Salome Zourabichvili, at odds with parliament, remains a focal point of the opposition.",
        countries: [
          { name: 'Georgia', flag: '🇬🇪', role: 'Belligerent' },
          { name: 'European Union', flag: '🇪🇺', role: 'Mediator' },
          { name: 'Russia', flag: '🇷🇺', role: 'Observer' },
          { name: 'United States', flag: '🇺🇸', role: 'Observer' },
        ],
        tags: ['democracy', 'EU accession', 'protests', 'Russian influence'],
        events: [
          {
            id: 'geo-001',
            date: '2026-01-22',
            headline: "Protests resume in Tbilisi as EU suspends Georgia's candidate status review",
            summary:
              'Thousands gathered outside parliament for the 57th consecutive day of demonstrations. The EU formally suspended its annual progress review, citing insufficient democratic reforms and media freedom concerns.',
            sources: [
              { publisher: 'BBC News', url: 'https://www.bbc.com/news/world/europe' },
              { publisher: 'Civil.ge', url: 'https://civil.ge/' },
            ],
          },
          {
            id: 'geo-002',
            date: '2025-12-05',
            headline: 'US sanctions 15 Georgian officials over post-election violence',
            summary:
              'The US State Department announced visa restrictions and financial sanctions on Georgian law enforcement and government officials linked to the use of force against peaceful demonstrators following the disputed October 2024 parliamentary elections.',
            sources: [
              { publisher: 'US State Department', url: 'https://www.state.gov/press-releases/' },
              { publisher: 'The Guardian', url: 'https://www.theguardian.com/world/georgia' },
            ],
          },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // MIDDLE EAST
  // ═══════════════════════════════════════════════════════════════════════════
  {
    continent: 'Middle East',
    tensions: [
      {
        id: 'israel-hamas-war',
        name: 'Israel–Gaza War',
        continent: 'Middle East',
        status: 'critical',
        severity: 'high',
        startDate: '2023-10-07',
        lastUpdated: '2026-02-18',
        description:
          "The conflict erupted after Hamas's October 7, 2023 attack that killed approximately 1,200 Israelis and took ~250 hostages. Israel's military campaign in Gaza has caused massive civilian casualties and a humanitarian catastrophe. A fragile ceasefire brokered in January 2025 has seen multiple breakdowns; negotiations over a permanent end to hostilities and remaining hostages continue.",
        countries: [
          { name: 'Israel', flag: '🇮🇱', role: 'Belligerent' },
          { name: 'Palestine (Hamas)', flag: '🇵🇸', role: 'Belligerent' },
          { name: 'United States', flag: '🇺🇸', role: 'Ally' },
          { name: 'Egypt', flag: '🇪🇬', role: 'Mediator' },
          { name: 'Qatar', flag: '🇶🇦', role: 'Mediator' },
        ],
        tags: ['humanitarian crisis', 'ceasefire', 'hostages', 'ICJ', 'occupation'],
        events: [
          {
            id: 'igh-001',
            date: '2026-02-18',
            headline: 'Phase 2 ceasefire negotiations stall over IDF withdrawal timeline',
            summary:
              "Doha-hosted talks between Israeli and Hamas negotiators broke down over disagreement on the pace of Israeli Defense Forces' withdrawal from the Netzarim corridor. Hamas insisted on a complete withdrawal as a precondition; Israel proposed a phased approach.",
            sources: [
              { publisher: 'Al Jazeera', url: 'https://www.aljazeera.com/where/gaza/' },
              { publisher: 'The Times of Israel', url: 'https://www.timesofisrael.com/' },
            ],
          },
          {
            id: 'igh-002',
            date: '2026-02-10',
            headline: 'ICJ orders Israel to ensure unimpeded humanitarian access to Gaza',
            summary:
              'The International Court of Justice issued a binding order requiring Israel to take all necessary measures to ensure the unobstructed provision of humanitarian assistance in Gaza, citing an imminent risk of famine.',
            sources: [
              { publisher: 'International Court of Justice', url: 'https://www.icj-cij.org/en/press-releases' },
              { publisher: 'Reuters', url: 'https://www.reuters.com/world/middle-east/' },
            ],
          },
          {
            id: 'igh-003',
            date: '2026-01-28',
            headline: 'UN: Gaza death toll surpasses 50,000; 90% of population displaced',
            summary:
              'OCHA confirmed that documented fatalities in Gaza have exceeded 50,000, with 70% identified as women and children. 2.1 million Palestinians — effectively the entire strip population — are internally displaced.',
            sources: [
              { publisher: 'UN OCHA', url: 'https://www.ochaopt.org/' },
              { publisher: 'BBC News', url: 'https://www.bbc.com/news/world/middle-east' },
            ],
          },
        ],
      },
      {
        id: 'iran-israel-tensions',
        name: 'Iran–Israel Direct Confrontation',
        continent: 'Middle East',
        status: 'elevated',
        severity: 'high',
        startDate: '2024-04-01',
        lastUpdated: '2026-02-01',
        description:
          "After decades of shadow conflict, Iran and Israel exchanged direct strikes in April and October 2024, marking a dangerous escalation beyond proxy warfare. Iran's Axis of Resistance—Hezbollah, the Houthis, Hamas, and Iraqi militias—continues operations. Hezbollah agreed to a ceasefire in November 2024, but violations are reported regularly.",
        countries: [
          { name: 'Iran', flag: '🇮🇷', role: 'Aggressor' },
          { name: 'Israel', flag: '🇮🇱', role: 'Defender' },
          { name: 'United States', flag: '🇺🇸', role: 'Ally' },
          { name: 'Hezbollah (Lebanon)', flag: '🇱🇧', role: 'Proxy' },
        ],
        tags: ['nuclear program', 'proxy war', 'Axis of Resistance', 'IRGC'],
        events: [
          {
            id: 'iir-001',
            date: '2026-02-01',
            headline: 'IAEA: Iran enriching uranium to 60% at accelerated pace, stockpile near weapons-grade',
            summary:
              'The International Atomic Energy Agency quarterly report confirms Iran has expanded enrichment capacity at Fordow and Natanz, with a 60%-enriched uranium stockpile now sufficient for five nuclear devices if further enriched.',
            sources: [
              { publisher: 'IAEA', url: 'https://www.iaea.org/newscenter/pressreleases' },
              { publisher: 'Associated Press', url: 'https://apnews.com/hub/iran-nuclear' },
            ],
          },
          {
            id: 'iir-002',
            date: '2025-12-18',
            headline: 'Israel conducts airstrike on Iranian-backed militia command in Syria',
            summary:
              'Israeli Air Force F-35s struck an IRGC-linked command and coordination center near Damascus, killing a senior Quds Force commander. Iran vowed a "proportional response."',
            sources: [
              { publisher: 'Haaretz', url: 'https://www.haaretz.com/' },
              { publisher: 'Syrian Observatory for Human Rights', url: 'https://www.syriahr.com/en/' },
            ],
          },
        ],
      },
      {
        id: 'houthi-red-sea',
        name: 'Houthi Red Sea Campaign',
        continent: 'Middle East',
        status: 'elevated',
        severity: 'medium',
        startDate: '2023-11-19',
        lastUpdated: '2026-02-15',
        description:
          "Yemen's Houthi movement (Ansar Allah) began attacking commercial shipping and Israeli-linked vessels in the Red Sea and Gulf of Aden to pressure Israel over Gaza. A US-UK-led Operation Prosperity Guardian conducted hundreds of counter-strikes. Global shipping has been heavily rerouted, adding weeks and billions in costs to trade routes.",
        countries: [
          { name: 'Yemen (Houthis)', flag: '🇾🇪', role: 'Aggressor' },
          { name: 'United States', flag: '🇺🇸', role: 'Defender' },
          { name: 'United Kingdom', flag: '🇬🇧', role: 'Defender' },
          { name: 'Iran', flag: '🇮🇷', role: 'Supplier' },
        ],
        tags: ['shipping disruption', 'Red Sea', 'Suez Canal', 'anti-ship missiles'],
        events: [
          {
            id: 'hrs-001',
            date: '2026-02-15',
            headline: 'Houthis attack Indian Ocean vessel 1,200 km from Yemen coast — longest-range strike yet',
            summary:
              'A Houthi anti-ship ballistic missile struck the bulk carrier MV Pacific Jade approximately 1,200 km from the Yemeni coast in the northern Indian Ocean, demonstrating an expanded operational range that threatens alternate Cape of Good Hope shipping lanes.',
            sources: [
              { publisher: "Lloyd's List", url: 'https://lloydslist.maritimeintelligence.informa.com/' },
              { publisher: 'Reuters', url: 'https://www.reuters.com/world/middle-east/' },
            ],
          },
          {
            id: 'hrs-002',
            date: '2026-01-29',
            headline: 'US and UK conduct 40-target joint strike on Houthi missile infrastructure',
            summary:
              'Operation Prosperity Guardian forces, including USS Harry S. Truman carrier group and RAF Typhoon aircraft, struck radar installations, drone manufacturing facilities, and underground missile storage sites across three Yemeni governorates.',
            sources: [
              { publisher: 'US Department of Defense', url: 'https://www.defense.gov/News/' },
              { publisher: 'BBC News', url: 'https://www.bbc.com/news/world/middle-east' },
            ],
          },
        ],
      },
      {
        id: 'syrian-transition',
        name: 'Syria Post-Assad Transition',
        continent: 'Middle East',
        status: 'elevated',
        severity: 'medium',
        startDate: '2024-12-08',
        lastUpdated: '2026-02-12',
        description:
          "Following the fall of Bashar al-Assad's government in December 2024, Hayat Tahrir al-Sham (HTS)-led forces established a transitional governing authority in Damascus. The country faces fragmentation risks, resurgent ISIS cells in the desert interior, Turkish military presence in the north, and Israeli strikes on remaining weapons stockpiles.",
        countries: [
          { name: 'Syria (HTS-led)', flag: '🇸🇾', role: 'Belligerent' },
          { name: 'Turkey', flag: '🇹🇷', role: 'Ally' },
          { name: 'Israel', flag: '🇮🇱', role: 'Observer' },
          { name: 'Kurdish SDF', flag: '🏳️', role: 'Belligerent' },
          { name: 'United States', flag: '🇺🇸', role: 'Observer' },
        ],
        tags: ['transition', 'HTS', 'ISIS', 'reconstruction', 'sanctions relief'],
        events: [
          {
            id: 'syr-001',
            date: '2026-02-12',
            headline: 'ISIS claims coordinated attacks killing 40 in Deir ez-Zor and Raqqa',
            summary:
              'Islamic State sleeper cells launched near-simultaneous bomb and gun attacks against Syrian transitional security forces in eastern Syria, exploiting governance gaps in the post-Assad vacuum.',
            sources: [
              { publisher: 'SITE Intelligence Group', url: 'https://ent.siteintelgroup.com/' },
              { publisher: 'Al-Monitor', url: 'https://www.al-monitor.com/syria' },
            ],
          },
          {
            id: 'syr-002',
            date: '2026-01-22',
            headline: 'EU lifts most Syria economic sanctions to support transitional government',
            summary:
              'The European Union suspended the majority of its economic sanctions against Syria for an initial six-month renewable period, aiming to facilitate humanitarian aid delivery and private-sector investment in reconstruction.',
            sources: [
              { publisher: 'European Council', url: 'https://www.consilium.europa.eu/en/press/' },
              { publisher: 'Reuters', url: 'https://www.reuters.com/world/middle-east/' },
            ],
          },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // ASIA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    continent: 'Asia',
    tensions: [
      {
        id: 'taiwan-strait',
        name: 'Taiwan Strait Crisis',
        continent: 'Asia',
        status: 'elevated',
        severity: 'high',
        startDate: '2022-08-02',
        lastUpdated: '2026-02-16',
        description:
          "Cross-strait tensions have remained dangerously elevated since the PLA's largest-ever military exercises around Taiwan in August 2022. China has intensified \"gray zone\" operations — daily incursions across the median line, sand dredging near outlying islands, and information warfare. Taiwan's January 2024 elections reaffirmed the DPP's democratic mandate; Beijing escalated rhetoric in response.",
        countries: [
          { name: 'Taiwan', flag: '🇹🇼', role: 'Defender' },
          { name: 'China (PRC)', flag: '🇨🇳', role: 'Aggressor' },
          { name: 'United States', flag: '🇺🇸', role: 'Ally' },
          { name: 'Japan', flag: '🇯🇵', role: 'Observer' },
        ],
        tags: ['gray zone', 'TSMC', 'semiconductor supply chain', 'AUKUS', 'PLA exercises'],
        events: [
          {
            id: 'twn-001',
            date: '2026-02-16',
            headline: 'PLA Eastern Theater Command conducts 72-hour encirclement exercise around Taiwan',
            summary:
              "China's military announced \"Joint Sword-2026A\" — a 72-hour exercise featuring carrier strike group maneuvers, submarine activity, and simultaneous air and sea blockade simulation. 30 PLA aircraft crossed the median line.",
            sources: [
              { publisher: 'South China Morning Post', url: 'https://www.scmp.com/news/china/military' },
              { publisher: 'Taiwan MND', url: 'https://www.mnd.gov.tw/english/' },
            ],
          },
          {
            id: 'twn-002',
            date: '2026-01-28',
            headline: 'US Congress passes Taiwan Security Enhancement Act, authorizing $12B in military assistance',
            summary:
              'The US Senate passed bipartisan legislation authorizing $12 billion in Foreign Military Financing for Taiwan over five years, including provisions for pre-positioned munitions on the island and accelerated delivery of previously approved weapons systems.',
            sources: [
              { publisher: 'US Senate Committee on Foreign Relations', url: 'https://www.foreign.senate.gov/' },
              { publisher: 'Defense News', url: 'https://www.defensenews.com/' },
            ],
          },
          {
            id: 'twn-003',
            date: '2025-12-10',
            headline: 'China imposes new economic sanctions on Taiwanese defense firms',
            summary:
              'Beijing placed three major Taiwanese defense contractors on a restricted entity list, barring them from engaging in any trade with Chinese entities and freezing their assets in mainland China.',
            sources: [
              { publisher: 'Reuters', url: 'https://www.reuters.com/world/asia-pacific/' },
              { publisher: 'Bloomberg', url: 'https://www.bloomberg.com/asia' },
            ],
          },
        ],
      },
      {
        id: 'north-korea-provocations',
        name: 'North Korea Missile Escalation',
        continent: 'Asia',
        status: 'elevated',
        severity: 'high',
        startDate: '2022-01-05',
        lastUpdated: '2026-02-08',
        description:
          'North Korea has conducted its most intensive ICBM and tactical weapons testing campaign in history, launching over 100 ballistic missiles since 2022. Pyongyang has deepened military cooperation with Russia, supplying artillery shells and deploying soldiers to the Ukraine front. Kim Jong-un declared a "permanent hostile relationship" with South Korea.',
        countries: [
          { name: 'North Korea', flag: '🇰🇵', role: 'Aggressor' },
          { name: 'South Korea', flag: '🇰🇷', role: 'Defender' },
          { name: 'United States', flag: '🇺🇸', role: 'Ally' },
          { name: 'Japan', flag: '🇯🇵', role: 'Defender' },
          { name: 'China', flag: '🇨🇳', role: 'Observer' },
          { name: 'Russia', flag: '🇷🇺', role: 'Ally' },
        ],
        tags: ['ICBM', 'nuclear', 'DPRK', 'Hwasong', 'Russia-DPRK axis'],
        events: [
          {
            id: 'nk-001',
            date: '2026-02-08',
            headline: 'DPRK launches Hwasong-19 ICBM; US NORTHCOM confirms intercontinental range',
            summary:
              'North Korea launched a Hwasong-19 solid-fuel ICBM on a lofted trajectory, flying 1,100 km before landing in waters east of Japan. US NORTHCOM confirmed the missile has the theoretical range to reach the continental United States with a warhead.',
            sources: [
              { publisher: 'NHK World', url: 'https://www3.nhk.or.jp/nhkworld/en/news/' },
              { publisher: 'US Northern Command', url: 'https://www.northcom.mil/News/' },
            ],
          },
          {
            id: 'nk-002',
            date: '2026-01-14',
            headline: 'Kim Jong-un oversees first tactical nuclear weapons live-fire drill',
            summary:
              "KCNA reported that Kim Jong-un personally supervised a drill involving 10 \"tactical nuclear warhead delivery systems,\" claiming the exercise validated North Korea's ability to deliver sub-kiloton nuclear payloads on short-range ballistic missiles.",
            sources: [
              { publisher: 'KCNA Watch (via Reuters)', url: 'https://www.reuters.com/world/asia-pacific/' },
              { publisher: '38 North', url: 'https://www.38north.org/' },
            ],
          },
        ],
      },
      {
        id: 'south-china-sea',
        name: 'South China Sea Disputes',
        continent: 'Asia',
        status: 'elevated',
        severity: 'medium',
        startDate: '2012-04-01',
        lastUpdated: '2026-02-11',
        description:
          "China claims approximately 90% of the South China Sea under its \"nine-dash line\" assertion, bringing it into direct conflict with the Philippines, Vietnam, Malaysia, and Brunei. The Spratly and Paracel Islands and Second Thomas Shoal are persistent flashpoints. China's coast guard has used water cannons, lasers, and physical blockades against Philippine vessels.",
        countries: [
          { name: 'China', flag: '🇨🇳', role: 'Aggressor' },
          { name: 'Philippines', flag: '🇵🇭', role: 'Defender' },
          { name: 'Vietnam', flag: '🇻🇳', role: 'Belligerent' },
          { name: 'United States', flag: '🇺🇸', role: 'Ally' },
          { name: 'Australia', flag: '🇦🇺', role: 'Observer' },
        ],
        tags: ['nine-dash line', 'UNCLOS', 'Second Thomas Shoal', 'freedom of navigation'],
        events: [
          {
            id: 'scs-001',
            date: '2026-02-11',
            headline: 'China coast guard fires water cannons at Philippine Navy resupply mission to BRP Sierra Madre',
            summary:
              'A Philippine Navy vessel conducting a routine resupply mission to the intentionally grounded BRP Sierra Madre on Second Thomas Shoal was intercepted by four Chinese coast guard vessels that deployed water cannons, damaging the Philippine ship and injuring three sailors.',
            sources: [
              { publisher: 'Philippine Coast Guard', url: 'https://coastguard.gov.ph/pressreleases/' },
              { publisher: 'Reuters', url: 'https://www.reuters.com/world/asia-pacific/' },
            ],
          },
          {
            id: 'scs-002',
            date: '2026-01-30',
            headline: 'US and Philippines conduct largest-ever Balikatan exercises with live-fire maritime drills',
            summary:
              'Over 16,000 US and Philippine troops participated in Balikatan 2026, which for the first time included live-fire sinking exercises targeting decommissioned vessels in the northern Philippine Sea, a clear signal aimed at China.',
            sources: [
              { publisher: 'US Indo-Pacific Command', url: 'https://www.pacom.mil/Media/News/' },
              { publisher: 'Philippine Daily Inquirer', url: 'https://newsinfo.inquirer.net/' },
            ],
          },
        ],
      },
      {
        id: 'india-pakistan-loc',
        name: 'India–Pakistan Line of Control',
        continent: 'Asia',
        status: 'watchlist',
        severity: 'medium',
        startDate: '1947-01-01',
        lastUpdated: '2026-01-25',
        description:
          'The contested Line of Control (LoC) in Jammu & Kashmir remains a persistent flashpoint. Cross-border infiltration by militant groups, ceasefire violations, and diplomatic tensions periodically spike. The 2021 ceasefire agreement has held with intermittent violations. Both countries maintain nuclear arsenals, making escalation risk a perpetual concern.',
        countries: [
          { name: 'India', flag: '🇮🇳', role: 'Belligerent' },
          { name: 'Pakistan', flag: '🇵🇰', role: 'Belligerent' },
          { name: 'China', flag: '🇨🇳', role: 'Ally' },
        ],
        tags: ['Kashmir', 'nuclear deterrence', 'ceasefire violations', 'cross-border terrorism'],
        events: [
          {
            id: 'ipk-001',
            date: '2026-01-25',
            headline: 'Pakistan claims Indian special forces violated LoC in Poonch sector',
            summary:
              "Pakistan's military spokesperson claimed Indian troops crossed the Line of Control near Poonch and engaged Pakistani border guards in a firefight, killing two Pakistani soldiers. India denied any violation, calling the claim \"fabricated.\"",
            sources: [
              { publisher: 'Dawn', url: 'https://www.dawn.com/' },
              { publisher: 'NDTV', url: 'https://www.ndtv.com/' },
            ],
          },
          {
            id: 'ipk-002',
            date: '2026-01-08',
            headline: 'Militant attack kills 12 Indian security personnel in Rajouri district',
            summary:
              "A coordinated ambush by suspected Lashkar-e-Taiba militants targeting an Indian Army convoy in Rajouri district killed 12 soldiers. India's National Investigation Agency linked the attack to handlers based in Pakistan-administered Kashmir.",
            sources: [
              { publisher: 'The Hindu', url: 'https://www.thehindu.com/' },
              { publisher: 'Associated Press', url: 'https://apnews.com/hub/india' },
            ],
          },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // AFRICA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    continent: 'Africa',
    tensions: [
      {
        id: 'sudan-civil-war',
        name: 'Sudan Civil War',
        continent: 'Africa',
        status: 'critical',
        severity: 'high',
        startDate: '2023-04-15',
        lastUpdated: '2026-02-17',
        description:
          "Fighting between Sudan's regular Armed Forces (SAF) and the paramilitary Rapid Support Forces (RSF) has created the world's largest displacement crisis. The RSF controls most of Darfur and large swaths of Khartoum, while the SAF retains the north and east. Atrocities, including mass rape, ethnically targeted killings, and deliberate attacks on hospitals, have been widely documented.",
        countries: [
          { name: 'Sudan (SAF)', flag: '🇸🇩', role: 'Belligerent' },
          { name: 'Sudan (RSF)', flag: '🇸🇩', role: 'Belligerent' },
          { name: 'Egypt', flag: '🇪🇬', role: 'Ally' },
          { name: 'UAE', flag: '🇦🇪', role: 'Supplier' },
          { name: 'Russia (Wagner)', flag: '🇷🇺', role: 'Supplier' },
        ],
        tags: ['humanitarian catastrophe', 'Darfur', 'mass displacement', 'famine', 'ICC'],
        events: [
          {
            id: 'sud-001',
            date: '2026-02-17',
            headline: 'RSF advances on El Fasher; UN warns of imminent genocide in North Darfur',
            summary:
              'The UN Special Adviser on the Prevention of Genocide issued a formal warning that RSF forces surrounding El Fasher — the last SAF-held city in Darfur — show "clear and credible risk" of committing genocide against the Masalit ethnic group.',
            sources: [
              { publisher: 'UN News', url: 'https://news.un.org/en/' },
              { publisher: 'Al Jazeera', url: 'https://www.aljazeera.com/where/sudan/' },
            ],
          },
          {
            id: 'sud-002',
            date: '2026-02-02',
            headline: "UNHCR: Sudan passes 12 million internally displaced, surpassing Syria as world's worst crisis",
            summary:
              "The UN Refugee Agency confirmed that Sudan's internal displacement has reached 12.1 million people, making it the world's largest internal displacement crisis, surpassing Syria. An estimated 25 million Sudanese face food insecurity.",
            sources: [
              { publisher: 'UNHCR', url: 'https://www.unhcr.org/sudan-emergency.html' },
              { publisher: 'Reuters', url: 'https://www.reuters.com/world/africa/' },
            ],
          },
          {
            id: 'sud-003',
            date: '2026-01-19',
            headline: 'ICC issues arrest warrants for three RSF commanders for crimes against humanity',
            summary:
              'The International Criminal Court issued arrest warrants for three senior RSF commanders, charging them with murder, rape, and pillaging as crimes against humanity in Khartoum and Darfur.',
            sources: [
              { publisher: 'International Criminal Court', url: 'https://www.icc-cpi.int/news' },
              { publisher: 'BBC Africa', url: 'https://www.bbc.com/news/world/africa' },
            ],
          },
        ],
      },
      {
        id: 'sahel-instability',
        name: 'Sahel Security Crisis',
        continent: 'Africa',
        status: 'elevated',
        severity: 'high',
        startDate: '2021-01-24',
        lastUpdated: '2026-02-09',
        description:
          'A wave of military coups in Mali (2021), Burkina Faso (2022), and Niger (2023) has upended the security architecture across the Sahel. The Alliance of Sahel States (AES) expelled French forces, withdrew from ECOWAS, and invited Russian Wagner Group operations. Islamist insurgencies (JNIM, ISGS) continue to expand territory and civilian casualties.',
        countries: [
          { name: 'Mali', flag: '🇲🇱', role: 'Belligerent' },
          { name: 'Burkina Faso', flag: '🇧🇫', role: 'Belligerent' },
          { name: 'Niger', flag: '🇳🇪', role: 'Belligerent' },
          { name: 'Russia (Africa Corps)', flag: '🇷🇺', role: 'Ally' },
          { name: 'France', flag: '🇫🇷', role: 'Observer' },
          { name: 'ECOWAS', flag: '🌍', role: 'Mediator' },
        ],
        tags: ['coups', 'Wagner/Africa Corps', 'jihadist insurgency', 'ECOWAS', 'anti-France'],
        events: [
          {
            id: 'sah-001',
            date: '2026-02-09',
            headline: 'JNIM jihadist attack kills 80 civilians in northern Burkina Faso market',
            summary:
              "Jama'at Nusrat al-Islam wal-Muslimin (JNIM) militants attacked a weekly market in the Sahel region of Burkina Faso, killing at least 80 civilians and wounding over 120, in one of the deadliest single attacks in the country since the coup.",
            sources: [
              { publisher: 'RFI (Radio France Internationale)', url: 'https://www.rfi.fr/en/africa/' },
              { publisher: 'Africa Confidential', url: 'https://www.africa-confidential.com/' },
            ],
          },
          {
            id: 'sah-002',
            date: '2025-12-28',
            headline: 'AES confederation formally dissolved ECOWAS membership; new security pact signed with Russia',
            summary:
              'The Alliance of Sahel States formally completed its withdrawal from ECOWAS, effective January 2026, and signed a mutual defense treaty with Russia that includes provisions for Russian military base access in each member country.',
            sources: [
              { publisher: 'Le Monde', url: 'https://www.lemonde.fr/en/africa/' },
              { publisher: 'Reuters', url: 'https://www.reuters.com/world/africa/' },
            ],
          },
        ],
      },
      {
        id: 'drc-eastern-conflict',
        name: 'DRC – M23/Rwanda Conflict',
        continent: 'Africa',
        status: 'critical',
        severity: 'high',
        startDate: '2021-11-01',
        lastUpdated: '2026-02-13',
        description:
          "The M23 rebel group, widely attributed to Rwandan backing, captured Goma — DRC's largest eastern city — in January 2025, triggering a massive humanitarian crisis. The Congolese government and Rwanda deny direct conflict while forces engage. SADC and EAC peacekeeping missions have failed to stabilize the region. Dozens of armed groups exploit the governance vacuum.",
        countries: [
          { name: 'DR Congo', flag: '🇨🇩', role: 'Defender' },
          { name: 'M23 Rebels', flag: '🏴', role: 'Aggressor' },
          { name: 'Rwanda', flag: '🇷🇼', role: 'Ally' },
          { name: 'SADC Mission', flag: '🌍', role: 'Mediator' },
          { name: 'Uganda', flag: '🇺🇬', role: 'Observer' },
        ],
        tags: ['minerals', 'Goma', 'Rwandan military', 'humanitarian crisis', 'MONUSCO'],
        events: [
          {
            id: 'drc-001',
            date: '2026-02-13',
            headline: 'M23 advances beyond Goma, captures Bukavu in South Kivu — 2 million flee',
            summary:
              "M23 forces extended their offensive south, capturing Bukavu, DRC's second-largest eastern city. Over 2 million people have now fled the combined Goma-Bukavu offensive, with hundreds of thousands sheltering in open fields without food or medical access.",
            sources: [
              { publisher: 'BBC Africa', url: 'https://www.bbc.com/news/world/africa' },
              { publisher: 'AFP', url: 'https://www.afp.com/en/news-hub/69/world' },
            ],
          },
          {
            id: 'drc-002',
            date: '2026-01-31',
            headline: 'US and EU sanction Rwanda officials over M23 support; Kigali denies',
            summary:
              "The United States and European Union imposed coordinated targeted sanctions on five senior Rwandan military and intelligence officials for providing command, logistical, and financial support to M23. Rwanda's foreign ministry called the measures \"baseless and politically motivated.\"",
            sources: [
              { publisher: 'US Treasury Department', url: 'https://home.treasury.gov/news/press-releases' },
              { publisher: 'Reuters', url: 'https://www.reuters.com/world/africa/' },
            ],
          },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // AMERICAS
  // ═══════════════════════════════════════════════════════════════════════════
  {
    continent: 'Americas',
    tensions: [
      {
        id: 'haiti-crisis',
        name: 'Haiti Political & Gang Crisis',
        continent: 'Americas',
        status: 'critical',
        severity: 'high',
        startDate: '2021-07-07',
        lastUpdated: '2026-02-14',
        description:
          'Haiti is experiencing a catastrophic state collapse following the 2021 assassination of President Moïse. The Viv Ansanm gang coalition controls approximately 80% of Port-au-Prince. A Kenya-led Multinational Security Support (MSS) mission is operational but under-resourced. A transitional presidential council is attempting to organize elections.',
        countries: [
          { name: 'Haiti', flag: '🇭🇹', role: 'Defender' },
          { name: 'Kenya', flag: '🇰🇪', role: 'Ally' },
          { name: 'United States', flag: '🇺🇸', role: 'Supplier' },
          { name: 'Canada', flag: '🇨🇦', role: 'Supplier' },
        ],
        tags: ['gang warfare', 'state collapse', 'MSS mission', 'humanitarian crisis', 'elections'],
        events: [
          {
            id: 'hti-001',
            date: '2026-02-14',
            headline: 'Viv Ansanm gangs storm main Port-au-Prince hospital, kidnap patients and staff',
            summary:
              'Armed gang members affiliated with the Viv Ansanm coalition raided the Hôpital Général de Port-au-Prince, abducting doctors, nurses, and patients. Médecins Sans Frontières withdrew all staff from the capital in response.',
            sources: [
              { publisher: 'Médecins Sans Frontières', url: 'https://www.msf.org/haiti' },
              { publisher: 'AP News', url: 'https://apnews.com/hub/haiti' },
            ],
          },
          {
            id: 'hti-002',
            date: '2026-01-28',
            headline: 'Kenya deploys additional 600 officers to MSS Haiti mission; total reaches 1,200',
            summary:
              "Kenya's National Police Service deployed its second contingent of 600 officers to Haiti under the UN-authorized Multinational Security Support mission, raising total MSS strength to approximately 1,200 personnel — still well below the 2,500 mandated by the UN Security Council.",
            sources: [
              { publisher: 'Nation Africa', url: 'https://nation.africa/kenya/' },
              { publisher: 'UN Security Council', url: 'https://www.un.org/securitycouncil/content/resolutions-adopted-security-council' },
            ],
          },
        ],
      },
      {
        id: 'venezuela-guyana-essequibo',
        name: 'Venezuela–Guyana Essequibo Dispute',
        continent: 'Americas',
        status: 'elevated',
        severity: 'medium',
        startDate: '2023-12-03',
        lastUpdated: '2026-01-28',
        description:
          "Venezuela reignited its long-standing claim over the Essequibo region (two-thirds of Guyana's territory) through a December 2023 referendum. Offshore oil discoveries by ExxonMobil, Shell, and others have made the dispute strategically vital. US and UK naval vessels have conducted freedom-of-navigation patrols near Guyana's coast.",
        countries: [
          { name: 'Venezuela', flag: '🇻🇪', role: 'Aggressor' },
          { name: 'Guyana', flag: '🇬🇾', role: 'Defender' },
          { name: 'Brazil', flag: '🇧🇷', role: 'Mediator' },
          { name: 'United States', flag: '🇺🇸', role: 'Ally' },
          { name: 'CARICOM', flag: '🌎', role: 'Mediator' },
        ],
        tags: ['territorial dispute', 'oil', 'Essequibo', 'ICJ', 'referendum'],
        events: [
          {
            id: 've-001',
            date: '2026-01-28',
            headline: "ICJ rejects Venezuela's request to halt Guyana's offshore oil development",
            summary:
              "The International Court of Justice rejected Venezuela's emergency interim measures request that sought to halt ExxonMobil-led drilling operations in the disputed Essequibo offshore block, allowing Guyana's oil production to continue.",
            sources: [
              { publisher: 'International Court of Justice', url: 'https://www.icj-cij.org/en/press-releases' },
              { publisher: 'Bloomberg', url: 'https://www.bloomberg.com/energy' },
            ],
          },
          {
            id: 've-002',
            date: '2026-01-10',
            headline: 'Venezuela deploys 5,000 additional troops to Essequibo border region',
            summary:
              "Venezuelan President Maduro ordered the deployment of 5,000 soldiers from the Bolivarian Army's 1st Armored Division to border positions adjacent to the Essequibo region, calling it a \"defensive measure\" against \"imperialist aggression.\"",
            sources: [
              { publisher: 'Reuters', url: 'https://www.reuters.com/world/americas/' },
              { publisher: 'El Nacional (Venezuela)', url: 'https://www.el-nacional.com/' },
            ],
          },
        ],
      },
      {
        id: 'mexico-cartel-violence',
        name: 'Mexico Cartel Insurgency',
        continent: 'Americas',
        status: 'elevated',
        severity: 'medium',
        startDate: '2006-12-11',
        lastUpdated: '2026-02-10',
        description:
          "Territorial fighting between CJNG, Sinaloa Cartel, and regional criminal organizations has displaced over 400,000 people in states including Chiapas, Guerrero, Michoacán, and Sinaloa. A Sinaloa Cartel leadership split triggered extreme intra-cartel violence. The US government's designation of cartels as Foreign Terrorist Organizations (FTOs) in 2025 has complicated the bilateral relationship.",
        countries: [
          { name: 'Mexico', flag: '🇲🇽', role: 'Defender' },
          { name: 'United States', flag: '🇺🇸', role: 'Observer' },
        ],
        tags: ['cartel', 'CJNG', 'Sinaloa', 'FTO designation', 'fentanyl', 'extradition'],
        events: [
          {
            id: 'mex-001',
            date: '2026-02-10',
            headline: 'CJNG convoy ambushes Mexican Army patrol in Chiapas, killing 11 soldiers',
            summary:
              'A column of approximately 60 CJNG fighters in armed trucks ambushed a Mexican Army convoy on the Tuxtla Gutiérrez–Ocosingo highway, killing 11 soldiers and wounding 9 in one of the deadliest attacks on Mexican security forces in years.',
            sources: [
              { publisher: 'El País América', url: 'https://elpais.com/mexico/' },
              { publisher: 'InSight Crime', url: 'https://insightcrime.org/news/mexico/' },
            ],
          },
          {
            id: 'mex-002',
            date: '2026-01-22',
            headline: 'Mexico extradites "El Mayo" Zambada to US, Sinaloa Cartel power vacuum deepens',
            summary:
              "Mexico extradited Ismael \"El Mayo\" Zambada, Sinaloa Cartel co-founder, to stand trial in New York, intensifying the leadership struggle between Zambada's faction and the Chapitos (sons of El Chapo Guzmán) that has left over 800 dead in six months.",
            sources: [
              { publisher: 'US DOJ', url: 'https://www.justice.gov/news' },
              { publisher: 'Washington Post', url: 'https://www.washingtonpost.com/world/americas/' },
            ],
          },
        ],
      },
    ],
  },

  // ═══════════════════════════════════════════════════════════════════════════
  // OCEANIA
  // ═══════════════════════════════════════════════════════════════════════════
  {
    continent: 'Oceania',
    tensions: [
      {
        id: 'pacific-geopolitics',
        name: 'Pacific Island Nations — China vs. US/Australia Influence',
        continent: 'Oceania',
        status: 'watchlist',
        severity: 'medium',
        startDate: '2022-04-19',
        lastUpdated: '2026-01-31',
        description:
          'China has intensified diplomatic and economic engagement across Pacific Island nations through infrastructure investment, security agreements, and debt-financing. The US, Australia, and New Zealand have responded with the "Partners in the Blue Pacific" initiative and accelerated aid commitments. The Solomon Islands, Kiribati, and Nauru-China relationship are key flashpoints.',
        countries: [
          { name: 'China', flag: '🇨🇳', role: 'Aggressor' },
          { name: 'Solomon Islands', flag: '🇸🇧', role: 'Observer' },
          { name: 'United States', flag: '🇺🇸', role: 'Observer' },
          { name: 'Australia', flag: '🇦🇺', role: 'Ally' },
          { name: 'New Zealand', flag: '🇳🇿', role: 'Ally' },
        ],
        tags: ['Pacific pivot', 'infrastructure diplomacy', 'debt trap', 'AUKUS', 'maritime access'],
        events: [
          {
            id: 'pac-001',
            date: '2026-01-31',
            headline: 'China completes military access facility in Solomon Islands near Guadalcanal',
            summary:
              'Satellite imagery analyzed by the Australian Strategic Policy Institute (ASPI) confirmed that construction of a Chinese-funded "dual-use" maritime facility on Guadalcanal Island, capable of berthing naval vessels, is now complete.',
            sources: [
              { publisher: 'ASPI (Australian Strategic Policy Institute)', url: 'https://www.aspi.org.au/' },
              { publisher: 'Radio New Zealand (RNZ)', url: 'https://www.rnz.co.nz/international/pacific-news' },
            ],
          },
          {
            id: 'pac-002',
            date: '2026-01-15',
            headline: 'Australia commits $3.8B "Pacific Engagement Plan" to counter Chinese influence',
            summary:
              "Australia's Prime Minister announced a A$3.8 billion, five-year engagement plan for Pacific nations, including new development finance, climate resilience funds, and a fast-track labour mobility scheme, explicitly framed as an alternative to Chinese financing.",
            sources: [
              { publisher: 'Australian Department of Foreign Affairs and Trade', url: 'https://www.dfat.gov.au/news' },
              { publisher: 'The Australian', url: 'https://www.theaustralian.com.au/' },
            ],
          },
        ],
      },
      {
        id: 'png-internal-conflict',
        name: 'Papua New Guinea Tribal Violence',
        continent: 'Oceania',
        status: 'elevated',
        severity: 'medium',
        startDate: '2024-01-17',
        lastUpdated: '2026-02-03',
        description:
          "Severe inter-tribal and inter-ethnic violence in Papua New Guinea's Highlands, Enga, and Southern Highlands provinces has killed thousands since 2024. Modern weapons — including military-grade assault rifles — have transformed traditional land and resource disputes into lethal conflicts that overwhelm PNG's limited police and military capacity. Australia has provided emergency security assistance.",
        countries: [
          { name: 'Papua New Guinea', flag: '🇵🇬', role: 'Defender' },
          { name: 'Australia', flag: '🇦🇺', role: 'Ally' },
        ],
        tags: ['tribal violence', 'illegal weapons', 'resource conflict', 'aid dependency'],
        events: [
          {
            id: 'png-001',
            date: '2026-02-03',
            headline: 'Inter-tribal clashes in Enga Province kill 60, displace 15,000 in 72 hours',
            summary:
              'Three days of fighting between the Komia and Maip tribes in Enga Province left at least 60 dead and 15,000 displaced. PNG Defense Force troops were deployed but struggled to access affected villages due to damaged roads.',
            sources: [
              { publisher: 'Radio New Zealand (RNZ)', url: 'https://www.rnz.co.nz/international/pacific-news' },
              { publisher: 'AFP', url: 'https://www.afp.com/en/news-hub/69/world' },
            ],
          },
          {
            id: 'png-002',
            date: '2025-12-20',
            headline: 'Australia provides $120M emergency security package to PNG after highland killings',
            summary:
              'Australia announced an emergency A$120 million security assistance package for Papua New Guinea, including Blackhawk helicopter maintenance support, AFP police training, and CCTV infrastructure for Lae and Port Moresby.',
            sources: [
              { publisher: 'Australian DFAT', url: 'https://www.dfat.gov.au/news' },
              { publisher: 'The Guardian Australia', url: 'https://www.theguardian.com/australia-news' },
            ],
          },
        ],
      },
    ],
  },
];

// ─── Service functions ────────────────────────────────────────────────────────

export function getAllTensions(): ConflictTension[] {
  return CONTINENT_SECTIONS.flatMap((s) => s.tensions);
}

export function getFilteredContinentSections(
  filters: MonitorFilterState
): ContinentSection[] {
  const { statuses, severities, continents, searchQuery } = filters;
  const q = searchQuery.toLowerCase().trim();

  return CONTINENT_SECTIONS.map((section) => {
    if (continents.length > 0 && !continents.includes(section.continent)) {
      return { ...section, tensions: [] };
    }

    const filtered = section.tensions.filter((t) => {
      if (statuses.length > 0 && !statuses.includes(t.status)) return false;
      if (severities.length > 0 && !severities.includes(t.severity)) return false;
      if (q) {
        const haystack = [
          t.name,
          t.description,
          ...t.countries.map((c) => c.name),
          ...t.tags,
        ]
          .join(' ')
          .toLowerCase();
        if (!haystack.includes(q)) return false;
      }
      return true;
    });

    return { ...section, tensions: filtered };
  }).filter((s) => s.tensions.length > 0);
}

export function getSummaryStats() {
  const all = getAllTensions();
  return {
    total: all.length,
    critical: all.filter((t) => t.status === 'critical').length,
    elevated: all.filter((t) => t.status === 'elevated').length,
    watchlist: all.filter((t) => t.status === 'watchlist').length,
    resolved: all.filter((t) => t.status === 'resolved').length,
  };
}
